steps:
# stop server
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'compute'
#   - 'ssh'
#   - 'handeesofficial@handees-dev'
#   - '--tunnel-through-iap'
#   - '--project=handees'
#   - '--zone=europe-west6-a'
#   - '--command'
#   - 'pkill -f supervisord || true'
# copy changes to VM
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - 'compute'
#     - 'scp'
#     - '--tunnel-through-iap'
#     - '--recurse'
#     - '.'
#     - 'handees-dev:~/home/handeesofficial/backend'
#     - '--project=handees'
#     - '--zone=europe-west6-a'
# install dependencies
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'bash'
    - 'scripts/install_dependencies.sh'
  env:
    - 'APP_ENV=dev'
# start server
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'bash'
    - 'scripts/start_server.sh'
  env:
    - 'APP_ENV=dev'
