steps:
# stop server
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'compute'
#   - 'ssh'
#   - 'handeesofficial@handees-dev'
#   - '--tunnel-through-iap'
#   - '--project=handees'
#   - '--zone=europe-west6-a'
#   - '--command'
#   - 'pkill -f supervisord || true'
# copy changes to VM
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: /bin/sh
#   args:
#   - '-c'
#   - |
#     gcloud compute scp --recurse --zone europe-west6-a * \
#       'handeesofficial@handees-dev:/home/handeesofficial/backend' \
#       --tunnel-through-iap
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'scp'
    - '--tunnel-through-iap'
    - '--recurse'
    - '*'
    - 'handeesofficial@handees-dev:/home/handeesofficial/backend'
    - '--project=handees'
    - '--zone=europe-west6-a'
# install dependencies
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'bash'
    - '/home/handeesofficial/backend/scripts/install_dependencies.sh'
  env:
    - 'APP_ENV=dev'
# start server
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'bash'
    - '/home/handeesofficial/backend/scripts/start_server.sh'
  env:
    - 'APP_ENV=dev'
