steps:
# stop server
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'compute'
#   - 'ssh'
#   - 'handeesofficial@handees-dev'
#   - '--tunnel-through-iap'
#   - '--project=handees'
#   - '--zone=europe-west6-a'
#   - '--command'
#   - 'pkill -f supervisord || true'
# copy changes to VM
# https://hodo.dev/posts/post-14-cloud-build-iap/
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud compute scp --recurse --zone europe-west6-a * \
      'handeesofficial@handees-dev:/home/handeesofficial/backend' \
      --tunnel-through-iap
# install dependencies
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'echo "APP_ENV=dev" > /tmp/APP_ENV.env'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'handeesofficial@handees-dev'
  - '--tunnel-through-iap'
  - '--project=handees'
  - '--zone=europe-west6-a'
  - '--'
  - 'bash'
  - '/home/handeesofficial/backend/scripts/install_dependencies.sh'
# start server
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'handeesofficial@handees-dev'
    - '--tunnel-through-iap'
    - '--project=handees'
    - '--zone=europe-west6-a'
    - '--'
    - 'bash'
    - '/home/handeesofficial/backend/scripts/start_server.sh'