version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoints/entrypoint.sh
    volumes:
      - .:/usr/src/backend
      - ./migrations:/usr/src/backend/migrations
    ports:
      - 5020:5000
    env_file: 
      - ./.env
    depends_on:
      - db
    container_name: hbackend
    restart: unless-stopped
    logging:
      driver: local
      options:
        mode: non-blocking
        max-file: "3"
        max-size: "10m"
  
  huey-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoints/huey_point.sh
    volumes:
      - .:/usr/src/huey-backend
    env_file: 
      - ./.env
    depends_on:
      - db
      - backend
    container_name: huey-backend
    restart: unless-stopped
    logging:
      driver: local
      options:
        mode: non-blocking
        max-file: "3"
        max-size: "10m"
  
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: db
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    env_file:
      - ./.env
    logging:
    driver: local
    options:
      mode: non-blocking
      max-file: "3"
      max-size: "10m"
    restart: unless-stopped

  db-test:
    build:
        context: .
        dockerfile: Dockerfile-db
    hostname: db-test
    container_name: db-test
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=handeestestdb
    env_file:
      - ./.env.test
    logging:
      driver: local
      options:
        mode: non-blocking
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped

  redis:
    image: redis:6.2.6
    hostname: redis
    container_name: redish
    ports:
      - 6378:6378
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    logging:
      driver: local
      options:
        mode: non-blocking
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped

volumes:
  postgres_data:
