version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoints/entrypoint.sh
    volumes:
      - .:/usr/src/backend
      - ./migrations:/usr/src/backend/migrations
    ports:
      - 5020:5000
    env_file: 
      - ./.env
    depends_on:
      - db
      - rabbit
    container_name: hbackend
    restart: always
  
  huey-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoints/huey_point.sh
    volumes:
      - .:/usr/src/huey-backend
    env_file: 
      - ./.env
    depends_on:
      - db
      - backend
    container_name: huey-backend
    restart: always
  
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: db
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    env_file:
      - ./.env
  
  redis:
    image: redis:6.2.6
    hostname: redis
    container_name: redish
    ports:
      - 6378:6378
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

volumes:
  postgres_data:
