version: '3.8'

services:
  backend:
    build: .
    command: flask run
    volumes:
      - .:/usr/src/backend
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
volumes:
  postgres_data:
