version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/usr/src/backend
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
  
volumes:
  postgres_data: