[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)
chmod=0770 ; socket file mode (default 0700)
chown=handeesofficial:handeesofficial # https://github.com/Supervisor/supervisor/issues/173

[supervisorctl]
serverurl = unix:///tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=true               ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# [program:nginx]
# # command=/bin/sh /home/handeesofficial/backend/nginx/start.sh
# command=/usr/sbin/nginx -g 'daemon off;'  # https://serverfault.com/questions/647357/running-and-monitoring-nginx-with-supervisord
# directory=/home/handeesofficial/backend
# user=root
# autostart=true
# autorestart=true
# redirect_stderr=true

[program:handees1]
command=/home/handeesofficial/backend/env/bin/gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5000 wsgi:app
directory=/home/handeesofficial/backend
user=handeesofficial
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
environment=HOME="/home/handeesofficial"


# [program:handees2]
# command=/home/handeesofficial/backend/env/bin/gunicorn --worker-class eventlet -w 1 -b localhost:5001 wsgi:app
# directory=/home/handeesofficial/backend
# user=handeesofficial
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# stdout_logfile = /dev/stdout
# stderr_logfile = /dev/stderr
# stdout_logfile_maxbytes=0
# stdout_logfile_backups=0
# stderr_logfile_maxbytes=0
# stderr_logfile_backups=0
# environment=HOME="/home/handeesofficial"


# [program:handees3]
# command=/home/handeesofficial/backend/env/bin/gunicorn --worker-class eventlet -w 1 -b localhost:5002 wsgi:app
# directory=/home/handeesofficial/backend
# user=handeesofficial
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# stdout_logfile = /dev/stdout
# stderr_logfile = /dev/stderr
# stdout_logfile_maxbytes=0
# stdout_logfile_backups=0
# stderr_logfile_maxbytes=0
# stderr_logfile_backups=0

[program:huey]
command=/home/handeesofficial/backend/env/bin/huey_consumer.py huey_worker.huey -w 2 -n
directory=/home/handeesofficial/backend
user=handeesofficial
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
environment=HOME="/home/handeesofficial"