"""empty message

Revision ID: 5a81ea4412cd
Revises: cf33840137fb
Create Date: 2022-09-16 21:28:24.688530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a81ea4412cd'
down_revision = 'cf33840137fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'settlement_type',
               existing_type=postgresql.ENUM('NEGOTIATION', 'HOURLY_RATE', name='settlementenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'settlement_type',
               existing_type=postgresql.ENUM('NEGOTIATION', 'HOURLY_RATE', name='settlementenum'),
               nullable=False)
    # ### end Alembic commands ###
