"""empty message

Revision ID: 4540c18e59f9
Revises: a3c9702ae7eb
Create Date: 2022-09-29 03:27:18.234073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4540c18e59f9'
down_revision = 'a3c9702ae7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
