"""empty message

Revision ID: cf33840137fb
Revises: ede95be9c720
Create Date: 2022-09-05 10:19:23.621494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'cf33840137fb'
down_revision = 'ede95be9c720'
branch_labels = None
depends_on = None


payment_option = postgresql.ENUM(
    "CASH",
    "CARD",
    name="paymentmethodenum"
)


def upgrade():
    payment_option.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', payment_option, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'method')

    bind = op.get_bind()
    payment_option.drop(bind, checkfirst=False)
    # ### end Alembic commands ###
