"""empty message

Revision ID: 2700e1766d64
Revises: 4170b2da049c
Create Date: 2022-08-26 05:17:52.455609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2700e1766d64'
down_revision = '4170b2da049c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisan', sa.Column('jobs_completed', sa.Integer(), nullable=True))
    op.drop_column('artisan', 'job_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisan', sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('artisan', 'jobs_completed')
    # ### end Alembic commands ###
