"""empty message

Revision ID: ede95be9c720
Revises: 640f264b8ea8
Create Date: 2022-09-05 10:17:09.623864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede95be9c720'
down_revision = '640f264b8ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
