"""empty message

Revision ID: 280ac11a57ca
Revises: 2700e1766d64
Create Date: 2022-09-01 07:04:04.657397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '280ac11a57ca'
down_revision = '2700e1766d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('settlement_type', sa.Enum('NEGOTIATION', 'HOURLY_RATE', name='settlementenum'), nullable=False))

    op.drop_column('booking_contract', 'settlement_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_contract', sa.Column('settlement_type', postgresql.ENUM('NEGOTIATION', 'HOURLY_RATE', name='settlementenum'), autoincrement=False, nullable=False))

    op.drop_column('booking', 'settlement_type')
    # ### end Alembic commands ###
