"""empty message

Revision ID: a3c9702ae7eb
Revises: 5a81ea4412cd
Create Date: 2022-09-29 03:23:00.315581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c9702ae7eb'
down_revision = '5a81ea4412cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_auth',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('last_four', sa.String(), nullable=True),
    sa.Column('exp_month', sa.String(), nullable=True),
    sa.Column('exp_year', sa.String(), nullable=True),
    sa.Column('bin', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('reusable', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_code'),
    sa.UniqueConstraint('signature')
    )
    op.create_index(op.f('ix_card_auth_bank'), 'card_auth', ['bank'], unique=False)
    op.create_index(op.f('ix_card_auth_card_type'), 'card_auth', ['card_type'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_card_auth_card_type'), table_name='card_auth')
    op.drop_index(op.f('ix_card_auth_bank'), table_name='card_auth')
    op.drop_table('card_auth')
    # ### end Alembic commands ###
