"""updated models to include booking contract model

Revision ID: 75cfe04e5aee
Revises: ef7d6f22e0a2
Create Date: 2022-08-20 17:59:51.151917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cfe04e5aee'
down_revision = 'ef7d6f22e0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'booking_contract',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('booking_id', sa.String(), nullable=True),
        sa.Column('start_time', sa.Date(), nullable=True),
        sa.Column('end_time', sa.Date(), nullable=True),
        sa.Column('settlement_type', sa.Enum('NEGOTIATION', 'HOURLY_RATE', name='settlementenum'), nullable=False),
        sa.Column('agreed_start_time', sa.Date(), nullable=True),
        sa.Column('agreed_end_time', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('contract_type', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'booking', ['booking_id'])
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'booking', type_='unique')
    op.drop_column('booking', 'contract_type')
    op.drop_table('booking_contract')
    # ### end Alembic commands ###
