"""added kyc table to store records of kyc attempts made by artisans

Revision ID: d5f3bcdc9442
Revises: e1bc3dd79eb6
Create Date: 2023-09-02 07:32:41.488171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f3bcdc9442'
down_revision = 'e1bc3dd79eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'kyc',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('kyc_id', sa.String(length=200), nullable=False),
        sa.Column('kyc_type', sa.String(), nullable=True),
        sa.Column('drivers_license_number', sa.String(length=11), nullable=True),
        sa.Column('nin_number', sa.String(length=11), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('passport_number', sa.String(length=10), nullable=True),
        sa.Column('artisan_id', sa.String(length=200), nullable=True),
        sa.Column('image', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['artisan_id'], ['artisan.artisan_id'], ),
        sa.PrimaryKeyConstraint('kyc_id')
    )


def downgrade():
    op.drop_table('kyc')
    # ### end Alembic commands ###
