"""updates to card auth table

Revision ID: 79904e56d60b
Revises: 436703003dcb
Create Date: 2023-04-09 02:25:00.968289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79904e56d60b'
down_revision = '436703003dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('card_auth', sa.Column('brand', sa.String(), nullable=True))
    op.alter_column('card_auth', 'reusable', type_=sa.Boolean(), postgresql_using='reusable::boolean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_auth', 'brand')
    op.alter_column('card_auth', 'reusable', type_=sa.String())
    # ### end Alembic commands ###
