"""empty message

Revision ID: 93784d49f164
Revises: b4423178c4ae
Create Date: 2023-05-26 04:53:56.246916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from psycopg2.errors import NotNullViolation
from sqlalchemy.exc import IntegrityError

# revision identifiers, used by Alembic.
revision = '93784d49f164'
down_revision = 'b4423178c4ae'
branch_labels = None
depends_on = None


contract_duration = postgresql.ENUM(
    'DAYS',
    'WEEKS',
    name='bookingcontractdurationenum'
)


def upgrade():
    # create custom enum
    contract_duration.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_contract', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('booking_contract', sa.Column('duration_unit', contract_duration, nullable=False))
    op.add_column('booking', sa.Column('details_confirmed', sa.Boolean(), default=False, nullable=False))
    # # Set a default value for the new column
    # op.execute("UPDATE booking SET details_confirmed = FALSE")
    # op.alter_column('booking', 'details_confirmed', existing_type=sa.Boolean(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_contract', 'duration_unit')

    bind = op.get_bind()
    contract_duration.drop(bind, checkfirst=False)
    op.drop_column('booking_contract', 'duration')
    op.drop_column('booking', 'details_confirmed')
    # ### end Alembic commands ###
