"""added transaction reference column to payments table

Revision ID: 3a94e2bd07c0
Revises: e7100729ae9b
Create Date: 2024-06-01 23:08:46.440241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a94e2bd07c0'
down_revision = 'e7100729ae9b'
branch_labels = None
depends_on = None


kycenum = postgresql.ENUM(
    'UNINITIALIZED',
    'IN_PROGRESS',
    'COMPLETED',
    name='kycenum',
    create_type=True
)

kycenum.create(op.get_bind())


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.alter_column('kyc_status',
               existing_type=postgresql.ENUM('UNINITIALIZED', 'IN_PROGRESS', 'COMPLETED', name='kycstatusenum'),
               type_=sa.Enum('UNINITIALIZED', 'IN_PROGRESS', 'COMPLETED', name='kycenum'),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_reference', sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            'payment_transaction_reference_key', ['transaction_reference']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_transaction_reference_key', type_='unique')
        batch_op.drop_column('transaction_reference')

    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.alter_column('kyc_status',
               existing_type=sa.Enum('UNINITIALIZED', 'IN_PROGRESS', 'COMPLETED', name='kycenum'),
               type_=postgresql.ENUM('UNINITIALIZED', 'IN_PROGRESS', 'COMPLETED', name='kycstatusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
