"""added payment_method column to bookings table

Revision ID: 641cd5fa9fca
Revises: e7100729ae9b
Create Date: 2024-06-03 01:50:40.108222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '641cd5fa9fca'
down_revision = 'e7100729ae9b'
branch_labels = None
depends_on = None


bookingpaymentmethod = postgresql.ENUM(
    'CASH',
    'CARD',
    name='bookingpaymentmethod',
    create_type=True
)

bookingpaymentmethod.create(op.get_bind())


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('CASH', 'CARD', name='bookingpaymentmethod'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('payment_method')


    # ### end Alembic commands ###
