"""empty message

Revision ID: 461700103f58
Revises: 0722831373eb
Create Date: 2025-06-14 03:45:34.922193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '461700103f58'
down_revision = '0722831373eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
        sa.Column('blob_id', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('blob_type', sa.Enum('USER_PROFILE', 'ARTISAN_PROFILE', 'USER_KYC', 'ARTISAN_KYC', 'BOOKING', name='blobtypes'), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('booking_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id'],),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'],),
        sa.PrimaryKeyConstraint('blob_id')
    )
    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blob_blob_type'), ['blob_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blob_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blob_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_blob_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blob_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blob_booking_id'))
        batch_op.drop_index(batch_op.f('ix_blob_user_id'))
        batch_op.drop_index(batch_op.f('ix_blob_filename'))
        batch_op.drop_index(batch_op.f('ix_blob_content_type'))
        batch_op.drop_index(batch_op.f('ix_blob_blob_type'))

    op.drop_table('blob')
    # ### end Alembic commands ###
