"""empty message

Revision ID: 42f4aaaab1a1
Revises: b8ec34f70d9c
Create Date: 2025-12-17 12:44:08.160967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42f4aaaab1a1'
down_revision = 'b8ec34f70d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('mobile_app_registration_token', sa.String(), nullable=True)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile_app_registration_token')
