"""empty message

Revision ID: b23f7efcdd83
Revises: 4ab2c89c1c92
Create Date: 2025-09-30 03:18:47.688035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b23f7efcdd83'
down_revision = '4ab2c89c1c92'
branch_labels = None
depends_on = None

transactionstatus = postgresql.ENUM(
    'DISPUTE',
    'ERROR',
    'PENDING',
    'REVERSED',
    'FAILED',
    'SUCCESS',
    name='transactionstatusenum',
    create_type=True
)

transactionstatus.create(op.get_bind())


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
        sa.Column('withdrawal_id', sa.String(), nullable=False),
        sa.Column('reference', sa.String(), nullable=True),
        sa.Column('transfer_code', sa.String(), nullable=True),
        sa.Column('artisan_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['artisan_id'], ['artisan.artisan_id'], ),
        sa.PrimaryKeyConstraint('withdrawal_id'),
        sa.UniqueConstraint('reference'),
        sa.UniqueConstraint('transfer_code')
    )

    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'REVERSED', 'DISPUTE', 'ERROR', 'PENDING', name='transactionstatusenum'), nullable=True))
        batch_op.drop_constraint(batch_op.f('wallet_transaction_transaction_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('wallet_transaction_transaction_id_fkey'), 'payment', ['transaction_id'], ['payment_id'])
        batch_op.drop_column('status')

    op.drop_table('withdrawals')
    op.execute("DROP TYPE transactionstatusenum")
    # ### end Alembic commands ###
