"""empty message

Revision ID: 0b3e7aac77c7
Revises: b1688f455b3f
Create Date: 2025-08-30 06:51:38.600251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b3e7aac77c7'
down_revision = 'b1688f455b3f'
branch_labels = None
depends_on = None

SEQUENCE_NAME = 'user_id_seq'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence(SEQUENCE_NAME)))
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'id', sa.Integer(),
                autoincrement=True
            )
        )

    proxy_table = table(
        'user',
        column('user_id', postgresql.VARCHAR),
        column('id', postgresql.INTEGER)
    )
    conn = op.get_bind()
    results = conn.execute(
        sa.select(proxy_table.c.user_id)
    ).fetchall()

    max_id = 0
    for i, result in enumerate(results):
        current_id = i + 1
        conn.execute(
            proxy_table.update().where(
                proxy_table.c.user_id == result[0]
            ).values(id=current_id)
        )
        if current_id > max_id:
            max_id = current_id

    if max_id > 0:
        op.execute(f"SELECT setval('{SEQUENCE_NAME}', {max_id})")

    op.alter_column(
        'user', 'id',
        existing_type=postgresql.INTEGER,
        existing_nullable=True,
        nullable=False,
        server_default=sa.text(f"nextval('{SEQUENCE_NAME}')")
    )

    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'img_id', sa.String(),
                nullable=False,
                unique=True
            )
        )
        batch_op.create_unique_constraint('uix_img_id', ['img_id'])
        batch_op.create_unique_constraint(
            'uix_user_blob_type_filename',
            ['user_id', 'blob_type', 'filename']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('blob', schema=None) as batch_op:
        batch_op.drop_index('uix_img_id')
        batch_op.drop_index('uix_user_blob_type_filename')
        batch_op.drop_column('img_id')

    op.execute(sa.text(f"DROP SEQUENCE IF EXISTS {SEQUENCE_NAME}"))
    # ### end Alembic commands ###
