"""empty message

Revision ID: b1688f455b3f
Revises: 191ed847374e
Create Date: 2025-08-19 22:56:39.393229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1688f455b3f'
down_revision = '191ed847374e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'rating',
                sa.Float(),
                nullable=False,
                server_default=sa.text('0.0')
            )
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'rating',
                sa.Float(),
                nullable=False,
                server_default=sa.text('0.0')
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.drop_column('rating')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
