"""empty message

Revision ID: b8ec34f70d9c
Revises: b23f7efcdd83
Create Date: 2025-10-13 14:53:43.845592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8ec34f70d9c'
down_revision = 'b23f7efcdd83'
branch_labels = None
depends_on = None

old_enum_name = 'bookingstatusenum'
new_enum_name = 'bookingstatusenum_new'
old_enum_values = (
    'IN_PROGRESS', 'COMPLETED',
    'ARTISAN_CANCELLED', 'CUSTOMER_CANCELLED',
    'ARTISAN_ARRIVED'
)
new_enum_values = (
    'IN_PROGRESS', 'COMPLETED',
    'ARTISAN_CANCELLED', 'CUSTOMER_CANCELLED',
    'ARTISAN_ARRIVED', 'PENDING',
    'ARTISAN_MATCHED'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE {new_enum_name} AS ENUM ({', '.join(f'\'{v}\'' for v in new_enum_values)})")
    op.alter_column(
        'booking', 'status',
        existing_type=postgresql.ENUM(*old_enum_values, name=old_enum_name),
        type_=postgresql.ENUM(*new_enum_values, name=new_enum_name),
        postgresql_using=f"status::text::{new_enum_name}"
    )
    op.execute(f"DROP TYPE {old_enum_name}")
    op.execute(f"ALTER TYPE {new_enum_name} RENAME TO {old_enum_name}")
    op.execute(sa.text(f"""
        UPDATE booking
        SET status = CASE
            WHEN status::text = 'IN_PROGRESS' THEN '{new_enum_values[0]}'::{old_enum_name}
            WHEN status::text = 'COMPLETED' THEN '{new_enum_values[1]}'::{old_enum_name}
            ELSE status
        END
    """))

    op.create_table('booking_workday',
        sa.Column('contract_id', sa.Integer(), nullable=True),
        sa.Column('booking_id', sa.String(), nullable=True),
        sa.Column('name', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='bookingworkdayenum'), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
        sa.ForeignKeyConstraint(['contract_id'], ['booking_contract.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_work_session',
        sa.Column('working_day_id', sa.Integer(), nullable=False),
        sa.Column('clock_in', sa.DateTime(), nullable=True),
        sa.Column('clock_out', sa.DateTime(), nullable=True),
        sa.Column('booking_id', sa.String(), nullable=False),
        # sa.Column('event_type', sa.Enum('CLOCK_IN', 'CLOCK_OUT', name='bookingclockeventtypeenum'), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['working_day_id'], ['booking_workday.id'], ),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_activated', sa.Boolean(),
                nullable=True, server_default='false'
            )
        )

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'clock_in_flag', sa.Boolean(),
                nullable=True, server_default='false'
            )
        )
        batch_op.add_column(
            sa.Column(
                'current_work_session_id',
                sa.Integer(),
                nullable=True
            )
        )
    op.execute(
        """
        ALTER TABLE booking
        ADD CONSTRAINT fk_current_work_session_id
        FOREIGN KEY (current_work_session_id)
        REFERENCES booking_work_session (id);
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE {old_enum_name}_old AS ENUM ({', '.join(f'\'{v}\'' for v in old_enum_values)})")
    op.alter_column(
        'booking', 'status',
        existing_type=postgresql.ENUM(*new_enum_values, name=old_enum_name),
        type_=postgresql.ENUM(*old_enum_values, name=f'{old_enum_name}_old'),
        postgresql_using=f"status::text::{old_enum_name}_old"
    )
    op.execute(f"DROP TYPE {old_enum_name}")
    op.execute(f"ALTER TYPE {old_enum_name}_old RENAME TO {old_enum_name}")
    op.execute(sa.text(f"""
        UPDATE booking
        SET status = CASE
            WHEN status::text = 'IN_PROGRESS' THEN '{old_enum_values[0]}'::{old_enum_name}
            WHEN status::text = 'COMPLETED' THEN '{old_enum_values[1]}'::{old_enum_name}
            WHEN status::text = 'PENDING' THEN NULL
            ELSE status
        END
    """))

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('is_activated')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('clock_in_flag')
        batch_op.drop_constraint('fk_current_work_session_id')
        batch_op.drop_column('current_work_session_id')

    op.drop_table('booking_work_session')
    op.drop_table('booking_workday')
    op.execute("DROP TYPE bookingworkdayenum")
    # ### end Alembic commands ###
