"""empty message

Revision ID: 1f8a77c36d5a
Revises: 641cd5fa9fca
Create Date: 2025-03-30 20:25:04.987364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f8a77c36d5a'
down_revision = '641cd5fa9fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_accounts',
        sa.Column('account_name', sa.String(), nullable=False),
        sa.Column('bank_code', sa.String(), nullable=False),
        sa.Column('account_number', sa.String(), nullable=False),
        sa.Column('bank_name', sa.String(), nullable=False),
        sa.Column('recipient_code', sa.String(), nullable=False),
        sa.Column('artisan_id', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['artisan_id'], ['artisan.artisan_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recipient_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_accounts')
    # ### end Alembic commands ###
