"""empty message

Revision ID: 4ab2c89c1c92
Revises: 16f917e0f7c7
Create Date: 2025-09-20 14:29:09.849575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab2c89c1c92'
down_revision = '16f917e0f7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('balance', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('artisan_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.artisan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transaction',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('WITHDRAWAL', 'DEPOSIT', name='wallettransactionenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment.payment_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transaction_transaction_type'), ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_transaction_type'))

    op.drop_table('wallet_transaction')
    op.drop_table('wallet')
    op.execute("DROP TYPE wallettransactionenum")
    # ### end Alembic commands ###
