"""empty message

Revision ID: 16f917e0f7c7
Revises: 0b3e7aac77c7
Create Date: 2025-09-01 10:24:21.024944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16f917e0f7c7'
down_revision = '0b3e7aac77c7'
branch_labels = None
depends_on = None

# old_enum = postgresql.ENUM(
#     'IN_PROGRESS', 'COMPLETED',
#     'CANCELLED', 'ARTISAN_ARRIVED',
#     name='bookingstatusenum'
# )
# new_enum = postgresql.ENUM(
#     'IN_PROGRESS', 'COMPLETED', 'ARTISAN_CANCELLED',
#     'CUSTOMER_CANCELLED', 'ARTISAN_ARRIVED',
#     name='bookingstatusenum'
# )
old_enum_name = 'bookingstatusenum'
new_enum_name = 'bookingstatusenum_new'
old_enum_values = ('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARTISAN_ARRIVED')
new_enum_values = ('IN_PROGRESS', 'COMPLETED', 'ARTISAN_CANCELLED', 'CUSTOMER_CANCELLED', 'ARTISAN_ARRIVED')


def upgrade():
    op.execute(f"CREATE TYPE {new_enum_name} AS ENUM ({', '.join(f'\'{v}\'' for v in new_enum_values)})")
    op.alter_column(
        'booking', 'status',
        existing_type=postgresql.ENUM(*old_enum_values, name=old_enum_name),
        type_=postgresql.ENUM(*new_enum_values, name=new_enum_name),
        postgresql_using=f"status::text::{new_enum_name}"
    )
    op.execute(f"DROP TYPE {old_enum_name}")
    op.execute(f"ALTER TYPE {new_enum_name} RENAME TO {old_enum_name}")
    op.execute(sa.text(f"""
        UPDATE booking
        SET status = CASE
            WHEN status::text = 'IN_PROGRESS' THEN '{new_enum_values[0]}'::{old_enum_name}
            WHEN status::text = 'COMPLETED' THEN '{new_enum_values[1]}'::{old_enum_name}
            ELSE status
        END
    """))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_contract_type'), ['contract_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_settlement_type'), ['settlement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE {old_enum_name}_old AS ENUM ({', '.join(f'\'{v}\'' for v in old_enum_values)})")
    op.alter_column(
        'booking', 'status',
        existing_type=postgresql.ENUM(*new_enum_values, name=old_enum_name),
        type_=postgresql.ENUM(*old_enum_values, name=f'{old_enum_name}_old'),
        postgresql_using=f"status::text::{old_enum_name}_old"
    )
    op.execute(f"DROP TYPE {old_enum_name}")
    op.execute(f"ALTER TYPE {old_enum_name}_old RENAME TO {old_enum_name}")
    op.execute(sa.text(f"""
        UPDATE booking
        SET status = CASE
            WHEN status::text = 'IN_PROGRESS' THEN '{old_enum_values[0]}'::{old_enum_name}
            WHEN status::text = 'COMPLETED' THEN '{old_enum_values[1]}'::{old_enum_name}
            ELSE status
        END
    """))
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_settlement_type'))
        batch_op.drop_index(batch_op.f('ix_booking_payment_method'))
        batch_op.drop_index(batch_op.f('ix_booking_customer_id'))
        batch_op.drop_index(batch_op.f('ix_booking_contract_type'))
        batch_op.drop_index(batch_op.f('ix_booking_category_id'))
        batch_op.drop_index(batch_op.f('ix_booking_artisan_id'))
    # ### end Alembic commands ###
