"""empty message

Revision ID: 191ed847374e
Revises: 461700103f58
Create Date: 2025-07-14 13:01:58.684724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '191ed847374e'
down_revision = '461700103f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('date_of_booking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_booking', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
