"""empty message

Revision ID: 94f1cc79bb84
Revises: 42f4aaaab1a1
Create Date: 2026-01-13 01:33:39.975178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94f1cc79bb84'
down_revision = '42f4aaaab1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('booking_id', sa.String(), nullable=True),
        sa.Column('closed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_table('chat_message',
        sa.Column('message_id', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('chat_id', sa.String(), nullable=True),
        sa.Column('sent_by', sa.String(), nullable=True),
        sa.Column('is_flagged', sa.Boolean(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
        sa.ForeignKeyConstraint(['sent_by'], ['user.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_sent_by'), ['sent_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_sent_by'))
        batch_op.drop_index(batch_op.f('ix_chat_message_chat_id'))

    op.drop_table('chat_message')
    op.drop_table('chat')
    # ### end Alembic commands ###
