"""empty message

Revision ID: ff4b80609faf
Revises: 94f1cc79bb84
Create Date: 2026-02-09 18:38:44.409988

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff4b80609faf"
down_revision = "94f1cc79bb84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.create_table(
        "reviews",
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("artisan_id", sa.String(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["artisan_id"],
            ["artisan.artisan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.booking_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            "ix_artisan_rating_weight", ["artisan_id", "weight"], unique=False
        )
        batch_op.create_index(
            "ix_user_rating_weight", ["user_id", "weight"], unique=False
        )

    with op.batch_alter_table("artisan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "no_of_bookings",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "no_of_ratings",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ratings_weighted_sum",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "no_of_bookings",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "no_of_ratings",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ratings_weighted_sum",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("ratings_weighted_sum")
        batch_op.drop_column("no_of_ratings")
        batch_op.drop_column("no_of_bookings")

    with op.batch_alter_table("artisan", schema=None) as batch_op:
        batch_op.drop_column("ratings_weighted_sum")
        batch_op.drop_column("no_of_ratings")
        batch_op.drop_column("no_of_bookings")

    op.create_table(
        "rating",
        sa.Column("created_at", sa.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("unique_rowid()"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("weight", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("artisan_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["artisan_id"], ["artisan.artisan_id"], name=op.f("rating_artisan_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("rating_user_id_fkey"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rating_pkey")),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index("ix_user_rating_weight")
        batch_op.drop_index("ix_artisan_rating_weight")

    op.drop_table("reviews")
    # ### end Alembic commands ###
