"""empty message

Revision ID: 5a01c2761e15
Revises: 2fd5771dab3b
Create Date: 2026-09-01 14:54:43.973885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a01c2761e15'
down_revision = '2fd5771dab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_booking_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('artisan_crbk_id', 'booking', ['current_booking_id'], ['booking_id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_address', sa.String(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('customer_address')

    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.drop_constraint('artisan_crbk_id', type_='foreignkey')
        batch_op.drop_column('current_booking_id')
